// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: inventory.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createInventoryItem = `-- name: CreateInventoryItem :one
INSERT INTO inventory_items (id, created_at, updated_at, name, description)
VAlUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, name, description
`

type CreateInventoryItemParams struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
	Description sql.NullString
}

func (q *Queries) CreateInventoryItem(ctx context.Context, arg CreateInventoryItemParams) (InventoryItem, error) {
	row := q.db.QueryRowContext(ctx, createInventoryItem,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Description,
	)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Description,
	)
	return i, err
}

const getAllInventoryItems = `-- name: GetAllInventoryItems :many
SELECT id, created_at, updated_at, name, description FROM inventory_items
`

func (q *Queries) GetAllInventoryItems(ctx context.Context) ([]InventoryItem, error) {
	rows, err := q.db.QueryContext(ctx, getAllInventoryItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryItem
	for rows.Next() {
		var i InventoryItem
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
