// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type InventoryCheckOut struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	InventoryItemID uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CheckedOutAt    time.Time
	CheckedInAt     sql.NullTime
}

type InventoryItem struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
	Description sql.NullString
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Username  string
	Password  string
	IsAdmin   sql.NullBool
	ApiKey    string
}
